name: quill_editor
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
    path: webview_flutter
  path: ^1.6.4
  event_bus: ^1.1.1
  mime: ^0.9.6+3
  keyboard_visibility: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.xunxin.quill_editor
        pluginClass: QuillEditorPlugin
      ios:
        pluginClass: QuillEditorPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/quill_editor/assets/icons/block-quote.png
    - packages/quill_editor/assets/icons/bold.png
    - packages/quill_editor/assets/icons/underline.png
    - packages/quill_editor/assets/icons/strikethrough.png
    - packages/quill_editor/assets/icons/italic.png
    - packages/quill_editor/assets/icons/code-view.png
    - packages/quill_editor/assets/icons/link.png
    - packages/quill_editor/assets/icons/list-ordered.png
    - packages/quill_editor/assets/icons/list-bullet.png
    - packages/quill_editor/assets/icons/image-plus.png
    - packages/quill_editor/quill/last/index.html
    - packages/quill_editor/quill/last/main.js
    - packages/quill_editor/quill/last/quill.css
    - packages/quill_editor/quill/last/quill.bubble.css
    - packages/quill_editor/quill/last/quill.js
    - packages/quill_editor/quill/last/quill.min.js
    - packages/quill_editor/quill/full.html
    - packages/quill_editor/quill/quill.min.js
    - packages/quill_editor/quill/jquery.js
    - packages/quill_editor/quill/quill.snow.css
    - packages/quill_editor/quill/highlight.min.js
    - packages/quill_editor/quill/katex.min.js
    - packages/quill_editor/quill/feed.xml
    - packages/quill_editor/quill/katex.min.css
    - packages/quill_editor/quill/monokai-sublime.min.css
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
